# .ruff.toml
# Dit bestand MOET UTF-8 zonder BOM zijn. Geen lege regel boven deze comment.

[tool.ruff]
select = ["E", "F", "I"]
fix = true
fixable = ["ALL"]
line-length = 100
respect-gitignore = true

[tool.ruff.per-file-ignores]
"agent/tasks/*.py" = ["E401"]