# .ruff.toml
# Let op: dit bestand MOET UTF-8 zonder BOM zijn. Geen lege regels boven deze comment.

[tool.ruff]
# Basisselectie: E (pycodestyle), F (pyflakes), I (import sort)
select = ["E", "F", "I"]
# Alle regels mogen automatisch gefixt worden waar mogelijk.
fix = true
fixable = ["ALL"]
# Houd de code compact maar leesbaar
line-length = 100
# Respecteer .gitignore
respect-gitignore = true

# Per-bestand uitzonderingen (voorbeeld)
[tool.ruff.per-file-ignores]
"agent/tasks/*.py" = ["E401"]
