[lint]
# Behoud standaardregels, maar laat Bugbear (B*) los voor nu
# en respecteer import-sorting (I) + Pyflakes (F) + Pycodestyle (E).
select = ["E", "F", "I"]
fixable = ["ALL"]

[lint.per-file-ignores]
# De agent-stubs hebben compacte importregels: die zijn oké.
"agent/tasks/*.py" = ["E401"]

# Optioneel: als er in jouw app nog B904's blijven sluimeren,
# kun je later gericht per directory B904 uitzetten, bv.:
#"modules/**.py" = ["B904"]
#"core-backend/**.py" = ["B904"]
