services:
  core-backend:
    build:
      context: ./core-backend
      dockerfile: Dockerfile
    expose:
      - "9000"
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=9000
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "9000"]
