services:
  core-traefik:
    image: traefik:2.11
    command:
      - --entrypoints.web.address=:80
      # Docker-provider aan
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # (optioneel debug/dashboard — alleen voor lokaal testen)
      # - --api.insecure=true
      # - --api.dashboard=true
    ports:
      - "10400:80"     # publiek entrypoint
      # - "10401:8080" # (optioneel) dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - core-backend
      - core-frontend
    restart: unless-stopped

  core-db:
    image: postgres:15
    environment:
      POSTGRES_DB: coredb
      POSTGRES_USER: coreapp
      POSTGRES_PASSWORD: coreapp_pw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - core_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  core-backend:
    build: ./core-backend
    environment:
      CORE_ENV: development
      CORE_JWT_ALG: RS256
      CORE_ACCESS_TTL_MIN: "20"
      CORE_REFRESH_TTL_DAYS: "14"
      CORE_ISSUER: http://core.local
      CORE_AUDIENCE: core-api
      CORE_CORS_ALLOWED_ORIGINS: http://localhost:10400,http://localhost:8200
      CORE_DB_HOST: core-db
      CORE_DB_PORT: "5432"
      CORE_DB_NAME: coredb
      CORE_DB_USER: coreapp
      CORE_DB_PASSWORD: coreapp_pw
      CORE_DB_SSLMODE: disable      # in prod: require
    depends_on:
      core-db:
        condition: service_healthy
    expose:
      - "9000"
    labels:
      - "traefik.enable=true"

      # -------- Router naar de API (hoge prioriteit) --------
      - "traefik.http.routers.core_api.rule=PathPrefix(`/api`) || PathPrefix(`/auth`) || PathPrefix(`/oauth`) || Path(`/healthz`) || Path(`/readyz`)"
      - "traefik.http.routers.core_api.entrypoints=web"
      - "traefik.http.routers.core_api.priority=100"
      - "traefik.http.services.core_api.loadbalancer.server.port=9000"

      # -------- (Optioneel) security & throttling via middlewares --------
      - "traefik.http.routers.core_api.middlewares=core-sec-headers,core-rate,core-retry"
      - "traefik.http.middlewares.core-sec-headers.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.core-sec-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.core-sec-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.core-sec-headers.headers.referrerPolicy=no-referrer"
      - "traefik.http.middlewares.core-sec-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.core-sec-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.core-sec-headers.headers.permissionsPolicy=geolocation=(), microphone=(), camera=()"
      - "traefik.http.middlewares.core-rate.ratelimit.average=100"
      - "traefik.http.middlewares.core-rate.ratelimit.burst=50"
      - "traefik.http.middlewares.core-retry.retry.attempts=3"
    restart: unless-stopped

  core-frontend:
    build: ./core-frontend
    expose:
      - "8200"
    labels:
      - "traefik.enable=true"

      # -------- Catch-all router voor FE (lagere prioriteit) --------
      - "traefik.http.routers.core_fe.rule=PathPrefix(`/`)"
      - "traefik.http.routers.core_fe.entrypoints=web"
      - "traefik.http.routers.core_fe.priority=1"
      - "traefik.http.services.core_fe.loadbalancer.server.port=8200"

      # -------- Dezelfde middlewares voor FE (veilig & beperkt) --------
      - "traefik.http.routers.core_fe.middlewares=core-sec-headers,core-rate,core-retry"
      - "traefik.http.middlewares.core-sec-headers.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.core-sec-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.core-sec-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.core-sec-headers.headers.referrerPolicy=no-referrer"
      - "traefik.http.middlewares.core-sec-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.core-sec-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.core-sec-headers.headers.permissionsPolicy=geolocation=(), microphone=(), camera=()"
      - "traefik.http.middlewares.core-rate.ratelimit.average=100"
      - "traefik.http.middlewares.core-rate.ratelimit.burst=50"
      - "traefik.http.middlewares.core-retry.retry.attempts=3"
    restart: unless-stopped

volumes:
  core_db_data:
