http:
  middlewares:
    core-sec-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        referrerPolicy: "no-referrer"
        contentTypeNosniff: true
        frameDeny: true
        permissionsPolicy: "geolocation=(), microphone=(), camera=()"
        browserXssFilter: true
        customResponseHeaders:
          X-Content-Type-Options: nosniff
    core-rate-limit:
      rateLimit:
        average: 100
        burst: 50
    core-retry:
      retry:
        attempts: 3
  routers:
    core_api_router:
      rule: "PathPrefix(`/api`) || PathPrefix(`/auth`) || PathPrefix(`/oauth`) || Path(`/healthz`) || Path(`/readyz`)"
      entryPoints: ["web"]
      service: core_api
      middlewares: ["core-sec-headers", "core-rate-limit", "core-retry"]
    core_fe_router:
      rule: "PathPrefix(`/`) && !PathPrefix(`/api`) && !PathPrefix(`/auth`) && !PathPrefix(`/oauth`) && !PathPrefix(`/healthz`) && !PathPrefix(`/readyz`)"
      entryPoints: ["web"]
      service: core_fe
      middlewares: ["core-sec-headers", "core-rate-limit", "core-retry"]
  services:
    core_api:
      loadBalancer:
        servers:
          - url: "http://core-backend:9000"
    core_fe:
      loadBalancer:
        servers:
          - url: "http://core-frontend:8200"
