name: Agent • PR Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: write
  checks: write
jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install agent deps
        run: |
          python -m pip install --upgrade pip
          pip install -r agent/requirements.txt
      - name: Lint / Type / Security
        run: |
          python agent/tasks/audit_core.py
      - name: (Optional) Build & Run backend for smoke
        run: |
          if [ -f core-backend/Dockerfile ]; then
            docker build -f core-backend/Dockerfile -t casuse-core-backend:ci .
            if [ -f docker-compose.ci.yml ]; then
              docker compose -f docker-compose.ci.yml up -d
              sleep 10
              docker compose -f docker-compose.ci.yml ps
              SMOKE_BASE="http://localhost:9000" python agent/cli.py smoke || true
              docker compose -f docker-compose.ci.yml down -v
            fi
          else
            echo "core-backend/Dockerfile not found – skipping smoke"; 
          fi
