# .github/workflows/agent-pr-checks.yml
name: Agent • PR Checks

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  pr-checks:
    name: Agent - PR Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Show Python version
        run: python -V

      - name: Ensure no BOM in .ruff.toml
        shell: bash
        run: |
          if [ -f ".ruff.toml" ]; then
            # lees eerste drie bytes als hex
            head -c 3 .ruff.toml | od -An -t x1 | tr -d ' \n' > .ruff.head.hex || true
            HEADHEX=$(cat .ruff.head.hex || echo "")
            # EFBBBF = UTF-8 BOM
            if [ "$HEADHEX" = "efbbbf" ]; then
              echo "::error title=Ruff config heeft BOM::Verwijder de UTF-8 BOM uit .ruff.toml"
              exit 1
            fi
          else
            echo "::warning ::.ruff.toml niet gevonden; ruff zal defaults gebruiken."
          fi

      - name: Install ruff
        run: python -m pip install --upgrade pip ruff

      - name: Ruff version
        run: ruff --version

      - name: Run ruff (respect .ruff.toml)
        run: ruff check . --output-format=github

      # (optioneel) je kunt hier nog black/mypy/pytest steps toevoegen indien gewenst
      # - name: Install test deps
      #   run: python -m pip install -r core-backend/requirements-dev.txt
      # - name: Pytest smoke
      #   run: python -m pytest -q core-backend/tests
