name: Agent • Scheduled Audit
on:
  workflow_dispatch:
  schedule:
    - cron: "15 3 * * *"
permissions:
  contents: read
  issues: write
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          pip install -r agent/requirements.txt
          python agent/cli.py audit | tee audit.json
      - uses: actions/upload-artifact@v4
        with: { name: audit-report, path: audit.json }
