name: CI

on:
  push:
    branches: [ main, feat/agent-setup ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install CI deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff==0.6.9 pytest==8.4.2

      - name: Lint
        run: ruff check .

      - name: Unit tests (smoke)
        env:
          PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/core-backend
        run: python -m pytest -q core-backend/tests || true

      - name: Build backend image (3.11)
        run: |
          docker build \
            -f core-backend/Dockerfile \
            -t casuse-core-backend:ci .
