name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, feat/agent-setup ]

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build core-backend image (Python 3.10)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: core-backend/Dockerfile
          push: false
          load: true
          build-args: |
            PYTHON_VERSION=3.10
          tags: casuse/core-backend:ci

      # plaats hier optioneel je scanstap (trivy/grype) als je die wilt houden
