name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build_and_scan:
    name: CI / build_and_scan (${{ github.event_name }})
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.6.9 pytest==8.4.2

      - name: Ensure .ruff.toml is UTF-8 (no BOM) and parseable
        run: |
          python - <<'PY'
          import pathlib, tomllib
          p = pathlib.Path(".ruff.toml")
          b = p.read_bytes()
          if b.startswith(b'\xef\xbb\xbf'):
              p.write_bytes(b[3:])
          tomllib.loads(p.read_text(encoding="utf-8"))
          print("OK: .ruff.toml is BOM-free & parseable")
          PY

      - name: Ruff (lint)
        run: ruff check .

      - name: Install runtime deps
        run: |
          pip install -r core-backend/requirements.txt
          pip install -r core-backend/requirements-dev.txt

      - name: Pytest (core-backend)
        run: python -m pytest -q core-backend/tests
