name: CI

on:
  push:
    branches: [ main, feat/**, fix/**, chore/** ]
  pull_request:
    branches: [ main ]

jobs:
  pr-checks:
    name: Agent • PR Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install agent deps
        run: |
          python -m pip install --upgrade pip
          pip install -r agent/requirements.txt

      - name: Lint / Type / Security (advisory)
        run: |
          set -e
          echo "::group::ruff"
          ruff check .
          echo "::endgroup::"

          echo "::group::mypy"
          # Advisory: exit code altijd 0, maar output blijft zichtbaar
          if ! mypy core-backend/app modules; then
            echo "mypy warnings detected (advisory)"; 
          fi
          echo "::endgroup::"

          echo "::group::bandit"
          # Advisory: niet-blockerend
          bandit -q -r core-backend/app modules || true
          echo "::endgroup::"

      - name: Compose config (sanity)
        run: |
          docker --version
          echo '{"ok": true}'

  build_and_scan:
    name: CI / build_and_scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build frontend (npm ci)
        working-directory: core-frontend
        run: |
          npm ci
          npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image (core-backend context)
        uses: docker/build-push-action@v6
        with:
          context: ./core-backend
          file: ./core-backend/Dockerfile
          push: false
          load: false
          tags: casuse-core-backend:test

  test:
    name: CI / test
    runs-on: ubuntu-latest
    needs: [ pr-checks, build_and_scan ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r core-backend/requirements.txt
          pip install -r core-backend/requirements-dev.txt

      - name: Run tests
        run: |
          python -m pytest -q core-backend/tests
